import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import img from "../public/image5.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dresses World | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Image
            src={img}
            className="shadow-md"
            priority="high"
            alt="homeimage"
            width={1200}
            height="auto"
          />
        </div>
      </main>
    </div>
  );
}
